### ISSUE TITLE
Null Reference error upon DeviceLoader intialization

### ISSUE THREAD

**Issue by cpellet** [akmadian/NZXTSharp#37] opened 2019-06-07 04:58 UTC
![image](https://user-images.githubusercontent.com/18552249/59082095-efb52e80-8923-11e9-9ab1-3869da9dc8e4.png)

**Comment by akmadian** [comment] 2019-06-07 05:47
Closing because #38 Is essentially the same issue, but it's more specific to the root cause.

**Closed by akmadian** 2019-06-07 05:47 UTC
